### PR TITLE
fix: ensure user messages are added to existing tasks

### LINKED ISSUE #136: [Bug]: `Task` doesn't contain full history
### What happened?

**Issue:**
When sending multiple messages to the same task (same `taskId`), the `Task.history` field only contains messages from the current turn instead of accumulating all historical messages. This is inconsistent with the Python SDK behavior.

**Expected Behavior:**
When continuing an existing task:
- Message 1 response: `task.history` = [user1, agent1]
- Message 2 response: `task.history` = [user1, agent1, user2, agent2]
- Message 3 response: `task.history` = [user1, agent1, user2, agent2, user3, agent3]

**Actual Behavior:**
- Message 1 response: `task.history` = [user1, agent1] ✅
- Message 2 response: `task.history` = [user2, agent2] ❌ (missing user1, agent1)
- Message 3 response: `task.history` = [user3, agent3] ❌ (missing all previous)

**Root Cause:**
The `DefaultRequestHandler`/`ResultManager` builds the task history from events published to the `ExecutionEventBus` during the current execution only. When a `RequestContext` contains an existing `task` with prior history, those historical messages are not republished to the event bus, causing them to be lost in the final response.

**Workaround:**
In the `AgentExecutor.execute()` method, manually republish historical messages before processing:

```typescript
if (task?.history && Array.isArray(task.history) && task.history.length > 0) {
    for (const historicalMessage of task.history) {
        eventBus.publish(historicalMessage);
    }
}
```

**Expected Fix:**
The SDK should automatically republish historical messages from `requestContext.task.history` when present, similar to how the Python SDK handles this scenario.

### Relevant log output

```shell

```

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by benclarkeio**
Ensured user messages are added to existing tasks, inline with the Python package:
- Added the latest user message to an existing `Task`'s history in the `RequestContext`
- Added the test "should return second task with full history if message is sent to an existing, non-terminal task"
- Updated `README.md` to check if a `Task` exists before publishing to the `eventBus`

# Description

Thank you for opening a Pull Request!
Before submitting your PR, there are a few things you can do to make sure it goes smoothly:

- [x] Follow the [`CONTRIBUTING` Guide](https://github.com/google-a2a/a2a-js/blob/main/CONTRIBUTING.md).
- [x] Make your Pull Request title in the <https://www.conventionalcommits.org/> specification.
  - Important Prefixes for [release-please](https://github.com/googleapis/release-please):
    - `fix:` which represents bug fixes, and correlates to a [SemVer](https://semver.org/) patch.
    - `feat:` represents a new feature, and correlates to a SemVer minor.
    - `feat!:`, or `fix!:`, `refactor!:`, etc., which represent a breaking change (indicated by the `!`) and will result in a SemVer major.
- [x] Ensure the tests and linter pass
- [x] Appropriate docs were updated (if necessary)

Fixes #136 🦕

### CODE REVIEW

**Comment by swapydapy** [comment]
Thanks for raising this PR. Will be reviewing it in some time.

File: src/server/request_handler/default_request_handler.ts [hunk 1]
```diff
@@ -80,6 +80,9 @@ export class DefaultRequestHandler implements A2ARequestHandler {
                 // Throw an error that conforms to the JSON-RPC Invalid Request error specification.
                 throw A2AError.invalidRequest(`Task ${task.id} is in a terminal state (${task.status.state}) and cannot be modified.`)
             }
+
+            // Add incomingMessage to history.
+            task.history = [...(task.history || []), incomingMessage];
         }
```
Comment (ishymko) [inline src/server/request_handler/default_request_handler.ts:87]: If we save the updated task here to taskStore, other changes shouldn't be necessary:

```ts
await this.taskStore.save(task);
```

File: test/server/default_request_handler.spec.ts [hunk 2]
```diff
@@ -242,6 +242,133 @@ describe('DefaultRequestHandler as A2ARequestHandler', () => {
         assert.include((nonBlockingTask.status.message?.parts[0] as any).text, errorMessage, 'Error message should be in the status');
     });
 
+    it('sendMessage: should return second task with full history if message is sent to an existing, non-terminal task', async () => {
```
Comment (ishymko) [inline test/server/default_request_handler.spec.ts:245]: Let's test `'artifact-update'` as well, currently removing added code there does not fail this test.

File: src/server/request_handler/default_request_handler.ts (hunk 1 above)
Comment (benclarkeio) [reply src/server/request_handler/default_request_handler.ts:87]: Done

File: test/server/default_request_handler.spec.ts (hunk 2 above)
Comment (benclarkeio) [reply test/server/default_request_handler.spec.ts:245]: With `await this.taskStore.save(task);` `status-update` and `artifact-update` are equivalent. Removing the code I added will break both and the test

Comment (ishymko) [reply test/server/default_request_handler.spec.ts:245]: True, but let's still add `artifact-update` here for completeness, better coverage and in case implementation changes.

File: src/server/result_manager.ts [hunk 3]
```diff
@@ -35,7 +35,6 @@ export class ResultManager {
         } else if (event.kind === 'task') {
             const taskEvent = event as Task;
             this.currentTask = { ...taskEvent }; // Make a copy
-
```
Comment (ishymko) [inline src/server/result_manager.ts:38]: super nit: let's completely get rid of diff in this file :)

**Review by ishymko — COMMENTED** [review]
Last minor things and should be good to go!

File: src/server/result_manager.ts (hunk 3 above)
Comment (benclarkeio) [reply src/server/result_manager.ts:38]: Done!

**Review by ishymko — APPROVED** [review]
🚀
