### PR TITLE
fix: enable follow up task issue on non blocking request

### LINKED ISSUE #156: [Bug]: A follow-up on a non blocking task, will return an error
### What happened?

If a followup on an existing running task is sent in a non blocking fashion, the error 
`Execution finished before a message or task was produced.`
Is returned

### Relevant log output

```shell

```

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by guglielmo-san**
# Description

This PR ensure that when a follow up task is sent to a task in a non final state using the NON blocking mode, the `_processEvents` will return the first available Message/Task status published on the bus, and will not throw an error. 
Follows the implementation of [Python SDK](https://github.com/guglielmo-san/a2a-python/blob/aa159f3e1076ae6eaad5576119d7857c2a9b2448/src/a2a/server/tasks/result_aggregator.py#L129)

This PR will make this [tck-test](https://github.com/guglielmo-san/a2a-tck/blob/test_javascript/a2a-tck/tests/mandatory/protocol/test_message_send_method.py#L150-L151) pass.
Thank you for opening a Pull Request!
Before submitting your PR, there are a few things you can do to make sure it goes smoothly:

- [x] Follow the [`CONTRIBUTING` Guide](https://github.com/google-a2a/a2a-js/blob/main/CONTRIBUTING.md).
- [x] Make your Pull Request title in the <https://www.conventionalcommits.org/> specification.
  - Important Prefixes for [release-please](https://github.com/googleapis/release-please):
    - `fix:` which represents bug fixes, and correlates to a [SemVer](https://semver.org/) patch.
    - `feat:` represents a new feature, and correlates to a SemVer minor.
    - `feat!:`, or `fix!:`, `refactor!:`, etc., which represent a breaking change (indicated by the `!`) and will result in a SemVer major.
- [x] Ensure the tests and linter pass
- [x] Appropriate docs were updated (if necessary)

Fixes #156  🦕

### CODE REVIEW

File: src/server/request_handler/default_request_handler.ts [hunk 1]
```diff
@@ -133,8 +133,14 @@ export class DefaultRequestHandler implements A2ARequestHandler {
                 await this._sendPushNotificationIfNeeded(event);
 
                 if (options?.firstResultResolver && !firstResultSent) {
-                    if (event.kind === 'message' || event.kind === 'task') {
-                        options.firstResultResolver(event as Message | Task);
+                    let firstResult: Message | Task | undefined;
+                    if (event.kind === 'message') {
+                        firstResult = event as Message;
```
Comment (ishymko) [inline src/server/request_handler/default_request_handler.ts]: nit: `as Message` shouldn't be mandatory here, as `event.kind === 'message'` above defines the type.
