### PR TITLE
fix: ensure push notifications order

### LINKED ISSUE #140: [Bug]: SendPushNotification does not implement any check to avoid race conditions
### What happened?

SendPushNotification does not guarantee that notifications will be sent in the correct order, which can lead to a race condition. This is already happening, as the RunUnitTest action appears to be flaky.

- https://github.com/a2aproject/a2a-js/actions/runs/18750636883 (see top right corner for first two failed attempts)
- https://github.com/a2aproject/a2a-js/actions/runs/17686476400

### Relevant log output

```shell

```

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by guglielmo-san**
# Description

This PR introduces a promise chain (`this.notificationChain`) to serialize the batches of notifications. This ensures that only one batch at a time is processed, in a predictable First-In, First-Out (FIFO) order. The test was already ensuring it and it caused some flakiness before, examples:
- https://github.com/a2aproject/a2a-js/actions/runs/18750636883 (see top right corner for first two failed attempts)
- https://github.com/a2aproject/a2a-js/actions/runs/17686476400

The `push_notification_integration.spec.ts` test file has been modified to simulate a more deterministic delay (100ms) on the completion of the first received notification. This guarantee a 100% test failure when the notification serialization is not implemented.

Thank you for opening a Pull Request!
Before submitting your PR, there are a few things you can do to make sure it goes smoothly:

- [x] Follow the [`CONTRIBUTING` Guide](https://github.com/google-a2a/a2a-js/blob/main/CONTRIBUTING.md).
- [x] Make your Pull Request title in the <https://www.conventionalcommits.org/> specification.
  - Important Prefixes for [release-please](https://github.com/googleapis/release-please):
    - `fix:` which represents bug fixes, and correlates to a [SemVer](https://semver.org/) patch.
    - `feat:` represents a new feature, and correlates to a SemVer minor.
    - `feat!:`, or `fix!:`, `refactor!:`, etc., which represent a breaking change (indicated by the `!`) and will result in a SemVer major.
- [x] Ensure the tests and linter pass
- [x] Appropriate docs were updated (if necessary)

Fixes #140  🦕

### CODE REVIEW

File: src/server/push_notification/default_push_notification_sender.ts [hunk 1]
```diff
@@ -33,11 +34,10 @@ export class DefaultPushNotificationSender implements PushNotificationSender {
...
-        pushConfigs.forEach(pushConfig => {
-            this._dispatchNotification(task, pushConfig)
-                .catch(error => {
-                    console.error(`Error sending push notification for task_id=${task.id} to URL: ${pushConfig.url}. Error:`, error);
-                });
+        // Ensures that notification are sent sequentially.
+        this.notificationChain = this.notificationChain.then(async () => {
+            const dispatches = pushConfigs.map(pushConfig => this._dispatchNotification(task, pushConfig));
+            await Promise.all(dispatches);
         });
```
[the remark this answers is not in the document]
Comment (ishymko) [reply src/server/push_notification/default_push_notification_sender.ts]: I'd put a catch explicitly on `_dispatchNotification` and remove it from the method itself, it doesn't throw now but it shouldn't be its' responsibility to never throw.

File: test/server/push_notification_integration.spec.ts [hunk 2]
```diff
@@ -47,7 +48,12 @@ describe('Push Notification Integration Tests', () => {
             app.use(express.json());
 
             // Endpoint to receive push notifications
-            app.post('/notify', (req: Request, res: Response) => {
+            app.post('/notify', async (req: Request, res: Response) => {
+                const status = req.body.status.state;
+                // Simulate delay for 'submitted' status to test correct ordering of notifications
+                if (status === 'submitted') {
+                    await new Promise(resolve => setTimeout(resolve, 100))
+                }
```
Comment (ishymko) [inline test/server/push_notification_integration.spec.ts]: Can this be moved into `/notify/:scenario`? Seems like it's there for cases like this.

File: src/server/push_notification/default_push_notification_sender.ts [hunk 3]
```diff
@@ -33,11 +34,10 @@ export class DefaultPushNotificationSender implements PushNotificationSender {
             return;
         }
 
-        pushConfigs.forEach(pushConfig => {
-            this._dispatchNotification(task, pushConfig)
-                .catch(error => {
-                    console.error(`Error sending push notification for task_id=${task.id} to URL: ${pushConfig.url}. Error:`, error);
-                });
+        // Ensures that notification are sent sequentially.
```
Comment (ishymko) [inline src/server/push_notification/default_push_notification_sender.ts]: nit: `in the same order they are sent`?

File: test/server/push_notification_integration.spec.ts
Comment (ishymko) [inline test/server/push_notification_integration.spec.ts:1]: Let's revert formatting changes in this file for now, we should run some repo-wise formatting separately.

File: src/server/push_notification/default_push_notification_sender.ts (hunk 1 above)
[the remark this answers is not in the document]
Comment (guglielmo-san) [reply src/server/push_notification/default_push_notification_sender.ts]: Done

File: src/server/push_notification/default_push_notification_sender.ts (hunk 3 above)
Comment (guglielmo-san) [reply src/server/push_notification/default_push_notification_sender.ts]: Done

File: test/server/push_notification_integration.spec.ts
Comment (guglielmo-san) [reply test/server/push_notification_integration.spec.ts:1]: Done

File: test/server/push_notification_integration.spec.ts [hunk 4]
```diff
@@ -58,9 +58,13 @@ describe('Push Notification Integration Tests', () => {
             });
 
             // Endpoint to simulate different response scenarios
-            app.post('/notify/:scenario', (req: Request, res: Response) => {
+            app.post('/notify/:scenario', async(req: Request, res: Response) => {
```
Comment (ishymko) [inline test/server/push_notification_integration.spec.ts]: nit: formatting `async (`

File: test/server/push_notification_integration.spec.ts (hunk 2 above)
Comment (guglielmo-san) [reply test/server/push_notification_integration.spec.ts]: Done

File: test/server/push_notification_integration.spec.ts
Comment (ishymko) [inline test/server/push_notification_integration.spec.ts:165]: Given that we now added 100ms into notifications sending, should we increase it? Probably worth looking into making it deterministic separately.

File: test/server/push_notification_integration.spec.ts [hunk 5]
```diff
@@ -620,4 +624,4 @@ describe('Push Notification Integration Tests', () => {
             });
         });
     });
-});
+});
```
Comment (ishymko) [inline test/server/push_notification_integration.spec.ts]: nit: formatting: let's keep new line at the end of file as before

File: test/server/push_notification_integration.spec.ts [hunk 6]
```diff
@@ -58,9 +58,13 @@ describe('Push Notification Integration Tests', () => {
             });
 
             // Endpoint to simulate different response scenarios
-            app.post('/notify/:scenario', (req: Request, res: Response) => {
+            app.post('/notify/:scenario', async(req: Request, res: Response) => {
                 const scenario = req.params.scenario;
-                
+                // Simulate delay for 'submitted' status to test correct ordering of notifications
+                if(scenario === 'delay_on_submitted' && req.body.status.state === 'submitted') {
```
Comment (ishymko) [inline test/server/push_notification_integration.spec.ts]: nit: formatting `if (`

**Review by ishymko — APPROVED** [review]

File: test/server/push_notification_integration.spec.ts (hunk 4 above)
Comment (guglielmo-san) [reply test/server/push_notification_integration.spec.ts]: Done

File: test/server/push_notification_integration.spec.ts (hunk 6 above)
Comment (guglielmo-san) [reply test/server/push_notification_integration.spec.ts]: Done

File: test/server/push_notification_integration.spec.ts (hunk 5 above)
Comment (guglielmo-san) [reply test/server/push_notification_integration.spec.ts]: Done

File: src/server/push_notification/default_push_notification_sender.ts [hunk 7]
```diff
@@ -33,11 +34,12 @@ export class DefaultPushNotificationSender implements PushNotificationSender {
             return;
         }
 
-        pushConfigs.forEach(pushConfig => {
-            this._dispatchNotification(task, pushConfig)
-                .catch(error => {
-                    console.error(`Error sending push notification for task_id=${task.id} to URL: ${pushConfig.url}. Error:`, error);
-                });
+        // Ensures that notification are delivered in the same order they are sent.
+        this.notificationChain = this.notificationChain.then(async () => {
```
Comment (swapydapy) [inline src/server/push_notification/default_push_notification_sender.ts]: Instead of using a promise chain, whose length will keep on increasing as notifs arrive, can we rather use a queue, denoted by a linked list.

As notifs get delivered, they can be removed from the queue. A dispatcher can keep reading from that queue.

Also, having a global queue is going to harm the throughput. This is going to be especially bad, when an A2A server is processing multiple tasks in parallel. Instead a task level queue should be added.

The entire task level notif queue can be cleaned once there are no more notifs to be delivered.

File: test/server/push_notification_integration.spec.ts [hunk 8]
```diff
@@ -58,9 +58,13 @@ describe('Push Notification Integration Tests', () => {
             });
 
             // Endpoint to simulate different response scenarios
-            app.post('/notify/:scenario', (req: Request, res: Response) => {
+            app.post('/notify/:scenario', async (req: Request, res: Response) => {
                 const scenario = req.params.scenario;
-                
+                // Simulate delay for 'submitted' status to test correct ordering of notifications
+                if (scenario === 'delay_on_submitted' && req.body.status.state === 'submitted') {
+                    await new Promise(resolve => setTimeout(resolve, 100));
```
Comment (swapydapy) [inline test/server/push_notification_integration.spec.ts]: Lets just minimise the delay to be 10ms. We should keep tests super fast.

Comment (swapydapy) [reply test/server/push_notification_integration.spec.ts]: Also there are other techniques to make testing time related code to be more deterministic, like simulated clock. But I guess can we keep using settimeout for now.

File: src/server/push_notification/default_push_notification_sender.ts (hunk 7 above)
Comment (ishymko) [reply src/server/push_notification/default_push_notification_sender.ts]: > having a global queue is going to harm the throughput

Very good point, indeed there is no reason to serialize notifications globally, we just need it per task.

> promise chain, whose length will keep on increasing as notifs arrive

I don't think this is the case here actually. As only one the most recent reference is kept, GC will get rid of resolved promises as they run, so the behaviour will be exactly as you described: a queue and JS runtime acting as a dispatcher. A small test:

```js
class Queue {
    constructor() { this.promiseChain = Promise.resolve(); }
    add(fn) { this.promiseChain = this.promiseChain.then(fn) }
}

function logMemory(label) {
    const mem = process.memoryUsage().heapUsed / 1024 / 1024;
    console.log(`${label}: ${mem.toFixed(2)} MB`);
}

const queue = new Queue();
for (let i = 1; i <= 1_000_000; i++) {
    if (i % 50_000 == 0) {
        queue.add(() => new Promise(res => setTimeout(res, 1000)));
        queue.promiseChain.then(() => logMemory(`Iteraion ${i}`))
        await new Promise(res => setTimeout(res, 1000))
    } else {
        queue.add(() => new Promise(res => res()))
    }
}
```

outputs

```
Iteraion 50000: 22.17 MB
Iteraion 100000: 28.20 MB
Iteraion 150000: 13.25 MB
Iteraion 200000: 14.87 MB
Iteraion 250000: 17.85 MB
Iteraion 300000: 17.87 MB
Iteraion 350000: 23.64 MB
Iteraion 400000: 24.92 MB
Iteraion 450000: 13.29 MB
Iteraion 500000: 14.92 MB
Iteraion 550000: 17.80 MB
Iteraion 600000: 17.86 MB
Iteraion 650000: 13.34 MB
Iteraion 700000: 14.98 MB
Iteraion 750000: 17.99 MB
Iteraion 800000: 18.00 MB
Iteraion 850000: 13.34 MB
Iteraion 900000: 14.91 MB
Iteraion 950000: 17.83 MB
Iteraion 1000000: 13.63 MB
```

While if it constantly increased, it'd look like this:

```js
const queue = []; // Just keep all refs to measure memory for 1M promises.
for (let i = 1; i <= 1_000_000; i++) {
    queue.push(() => new Promise(res => res()))
    if (i % 50_000 == 0) {
        logMemory(`Iteration ${i}`)
        await new Promise(res => setTimeout(res, 1000))
    }
}
```

outputs

```
Iteration 50000: 7.13 MB
Iteration 100000: 11.75 MB
Iteration 150000: 14.83 MB
Iteration 200000: 19.47 MB
Iteration 250000: 22.16 MB
Iteration 300000: 27.79 MB
Iteration 350000: 30.47 MB
Iteration 400000: 37.57 MB
Iteration 450000: 40.25 MB
Iteration 500000: 42.98 MB
Iteration 550000: 42.69 MB
Iteration 600000: 52.00 MB
Iteration 650000: 54.68 MB
Iteration 700000: 57.35 MB
Iteration 750000: 60.02 MB
Iteration 800000: 62.68 MB
Iteration 850000: 65.35 MB
Iteration 900000: 77.98 MB
Iteration 950000: 80.65 MB
Iteration 1000000: 83.33 MB
``` 

What do you think?

Comment (swapydapy) [reply src/server/push_notification/default_push_notification_sender.ts]: Hmm... I see, since we re-assign `this.promiseChain` to new then-promise, the earlier promise object is garbage collected. This is subtle and not explicit. Can we add a big comment explaining this, to make sure future readers are aware of this.

File: src/server/push_notification/default_push_notification_sender.ts [hunk 9]
```diff
@@ -33,11 +35,25 @@ export class DefaultPushNotificationSender implements PushNotificationSender {
...
+        // Chain promises to ensure notifications for the same task are sent sequentially.
+        // The `finally` block below will clean up the entry from the map once the
+        // promise chain for this task is complete.
+        const newPromise = this.notificationChain.get(task.id)!.then(async () => {
+            const dispatches = pushConfigs.map(pushConfig => this._dispatchNotification(task, pushConfig).catch((error) => { 
+                console.error(`Error sending push notification for task_id=${task.id} to URL: ${pushConfig.url}. Error:`, error);
+             }));
+            await Promise.all(dispatches);
+        })
+        this.notificationChain.set(task.id, newPromise);
```
Comment (ishymko) [inline src/server/push_notification/default_push_notification_sender.ts]: How about something like


```suggestion
        const lastPromise = this.notificationChain.get(task.id) ?? Promise.resolve();
        // Chain promises to ensure notifications for the same task are sent sequentially.
        // The `finally` block below will clean up the entry from the map once the
        // promise chain for this task is complete.
        const newPromise = lastPromise.then(async () => {
            const dispatches = pushConfigs.map(async pushConfig => {
                try {
                    await this._dispatchNotification(task, pushConfig)
                } catch (error) {
                    console.error(`Error sending push notification for task_id=${task.id} to URL: ${pushConfig.url}. Error:`, error)
                }
            });
            await Promise.all(dispatches);
        })
        this.notificationChain.set(task.id, newPromise);
```

File: test/server/push_notification_integration.spec.ts (hunk 8 above)
Comment (guglielmo-san) [reply test/server/push_notification_integration.spec.ts]: Creted a new issue to keep track of this
https://github.com/a2aproject/a2a-js/issues/148

File: src/server/push_notification/default_push_notification_sender.ts (hunk 9 above)
Comment (guglielmo-san) [reply src/server/push_notification/default_push_notification_sender.ts]: Sure, looks better

File: src/server/push_notification/default_push_notification_sender.ts (hunk 7 above)
Comment (guglielmo-san) [reply src/server/push_notification/default_push_notification_sender.ts]: Done

File: src/server/push_notification/default_push_notification_sender.ts [hunk 10]
```diff
@@ -33,11 +35,27 @@ export class DefaultPushNotificationSender implements PushNotificationSender {
...
+            const dispatches = pushConfigs.map(async pushConfig => {
+                try {
+                    await this._dispatchNotification(task, pushConfig)
+                } catch (error) {
+                    console.error(`Error sending push notification for task_id=${task.id} to URL: ${pushConfig.url}. Error:`, error)
+                }
+            });
+            await Promise.all(dispatches);
+        })
+        this.notificationChain.set(task.id, newPromise);
```
Comment (swapydapy) [inline src/server/push_notification/default_push_notification_sender.ts:52]: Can you add a comment explaining that previous promise objects will be garbage collected, as they get resolved. This will make sure memory doesn't linearly increase with number of notifs sent to a task.
