### PR TITLE
fix: do not use ReadableStream async iterator in SSE stream parsing

### LINKED ISSUE #308: [Bug]: value of response.body.pipeThrough is undefined (SSE)
### What happened?

On iOS, I'm seeing the logged error.

Looks like the `response.body.pipeThrough` from:
https://github.com/a2aproject/a2a-js/blob/3d9a052fe8cd917fcff1798b03a4865effabf0be/src/sse_utils.ts#L111
is not available on Safari.

### Relevant log output

```shell
n of e.body.pipeThrough is not a function.
In 'n of e.body.pipeThrough(new TextDecoderStream)', 'n of e.body.pipeThrough' is undefined
```

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by ilbertt**
# Description

The async iterator in `ReadableStream` is not available in browsers like Safari: [MDN](https://developer.mozilla.org/en-US/docs/Web/API/ReadableStream#browser_compatibility). This PR changes it to a lower-level API which has better support across different environments.

Fixes #308.

### CODE REVIEW

File: src/sse_utils.ts [hunk 1]
```diff
@@ -137,3 +137,43 @@ export async function* parseSseStream(
     yield { type: eventType, data: eventData };
   }
 }
+
+function createAsyncIterator(
+  stream: ReadableStream<string>
+): () => AsyncGenerator<Awaited<string>, void, unknown> {
```
[the remark this answers is not in the document]
Comment (ilbertt) [reply src/sse_utils.ts]: Fixed!

File: src/sse_utils.ts [hunk 2]
```diff
@@ -137,3 +137,43 @@ export async function* parseSseStream(
...
+ * @returns The stream with the async iterator
+ *
+ * @example
+ * ```ts
+ * for await (const value of pipeThrough(response.body)) {
+ *   console.log(value);
+ * }
+ * ```
+ */
+function pipeThrough(body: ReadableStream<Uint8Array<ArrayBuffer>>): ReadableStream<string> {
```
[the remark this answers is not in the document]
Comment (ilbertt) [reply src/sse_utils.ts]: @gemini-code-assist It actually does since the latest TS versions

File: src/sse_utils.ts [hunk 3]
```diff
@@ -137,3 +137,43 @@ export async function* parseSseStream(
...
+        if (done) {
+          break;
+        }
+        yield value;
+      }
+    } finally {
+      reader.releaseLock();
+    }
+  };
+}
```
Comment (ishymko) [inline src/sse_utils.ts]: What do you think about using this API always?

Something like

```ts
async function* readFrom(stream: ReadableStream<string>): AsyncGenerator<string, void, void> {
  const reader = stream.getReader();
  try {
    while (true) {
      const { done, value } = await reader.read();
      if (done) {
        break;
      }
      yield value;
    }
  } finally {
    reader.releaseLock();
  }
}
```

and then calling it in without patching logic

```ts
for await (const value of readFrom(response.body.pipeThrough(new TextDecoderStream())))
```

As we should either way write this code as a polyfill. Native implementation can be a bit faster but I don't think it's going be anything noticeable in the IO-bound context.

**Review by ishymko — COMMENTED** [review]
Thank you for the prompt fix!

BTW were you able to test it on a real iOS? We don't have this kind of integration tests running on a real iOS so if you were able to confirm it it'd be great.

**Comment by ilbertt** [comment]
> BTW were you able to test it on a real iOS? We don't have this kind of integration tests running on a real iOS so if you were able to confirm it it'd be great.

I tested the workaround from [my comment](https://github.com/a2aproject/a2a-js/issues/308#issuecomment-3783927607), and it was working. If you can release a beta/patch version, I'm happy to pull it in and test it

File: src/sse_utils.ts (hunk 3 above)
Comment (ilbertt) [reply src/sse_utils.ts]: Could make sense, although it also makes sense to show that we need a workaround for some environments in my opinion.

I agree the approach you proposed is cleaner though.

Comment (ishymko) [reply src/sse_utils.ts]: > also makes sense to show that we need a workaround for some environments in my opinion

Yeah, fair point. So how about always using the older API but with a comment linking to MDN?

This will also be enforced via a test you added. 

Patching approach is more advanced for sure and it makes use of built-in implementation when available, but in this case I'd prefer simplicity.

File: test/sse_utils.spec.ts [hunk 4]
```diff
@@ -174,4 +202,73 @@ describe('SSE Utils', () => {
...
+        if (parsedEvents.length === 1) {
+          break;
+        }
+      }
+
+      expect(parsedEvents).toHaveLength(1);
+      expect(JSON.parse(parsedEvents[0].data)).toEqual({ kind: 'first' });
+    });
+
+    it('should release reader lock when breaking early without async iterator', async () => {
```
Comment (ishymko) [inline test/sse_utils.spec.ts]: This test still passes with `reader.releaseLock();` commented out.

I tried to do `getReader()` and it also works outside of the loop even without `reader.releaseLock();`. It only fails inside the loop saying that the stream is locked (which makes sense).

Maybe GC does something for us in this case when reader goes out of scope, so not sure if it's possible to test properly.

File: test/sse_utils.spec.ts [hunk 5]
```diff
@@ -30,6 +30,34 @@ function createMockResponse(sseData: string, chunkSize: number = 2): Response {
...
+  const stream = new ReadableStream({
+    pull(controller) {
+      if (chunkIndex < chunks.length) {
+        controller.enqueue(chunks[chunkIndex]);
+        chunkIndex++;
+      } else {
+        controller.close();
+      }
+    },
+  });
```
Comment (ishymko) [inline test/sse_utils.spec.ts]: Looks redundant to me as there is only one chunk always.

Can we simplify here or simply extract stream creation part from `createMockResponse` into a separate function and call from both places?

File: test/sse_utils.spec.ts [hunk 6]
```diff
@@ -174,4 +202,73 @@ describe('SSE Utils', () => {
       expect(JSON.parse(parsedEvents[1].data)).toEqual(errorEvent);
     });
   });
+
+  describe('Async iterator fallback', () => {
```
Comment (ishymko) [inline test/sse_utils.spec.ts]: Should be possible to utilize existing `parseSseStream` tests by parametrizing via `describe.each` or similar.

As what we want to achieve is that everything works in both environments.

File: src/sse_utils.ts (hunk 3 above)
Comment (ilbertt) [reply src/sse_utils.ts]: Done!

File: test/sse_utils.spec.ts (hunk 5 above)
Comment (ilbertt) [reply test/sse_utils.spec.ts]: Refactored the test!

File: test/sse_utils.spec.ts (hunk 6 above)
Comment (ilbertt) [reply test/sse_utils.spec.ts]: Done!

File: test/sse_utils.spec.ts [hunk 7]
```diff
@@ -175,3 +209,58 @@ describe('SSE Utils', () => {
     });
   });
 });
+
+/**
+ * Tests that parseSseStream works correctly in both environments:
+ * - With native ReadableStream async iterator support
+ * - Without native async iterator (simulating older browsers/runtimes)
+ */
```
Comment (ishymko) [inline test/sse_utils.spec.ts]: Can we just modify existing tests under `describe('parseSseStream'` with the `.each` and pass those factory functions as you did here?

Comment (ilbertt) [reply test/sse_utils.spec.ts]: Ah, sorry. I didn't see those tests. I've pushed the change and removed my tests as they were pretty much duplicates
