### PR TITLE
fix: cancel/task now returns the expected 'cancelled' task status

### LINKED ISSUE #157: [Bug]: cancel/task does not return the task in status 'cancelled'
### What happened?

When the method `cancel/task` is called on a running task, it will return the correct task, but its status is not shown as `running`, but `canceled`

### Relevant log output

```shell

```

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by guglielmo-san**
# Description

The current implementation of the cancel/task did not return the task in 'cancelled' status, because it was not consuming all the events on the eventBus, but was taking the last published one.
This PR fixes this tck [test](https://github.com/guglielmo-san/a2a-tck/blob/9893cfdb5f5ab661958c3edcfad43be806ad5626/tests/mandatory/protocol/test_tasks_cancel_method.py#L39)

Thank you for opening a Pull Request!
Before submitting your PR, there are a few things you can do to make sure it goes smoothly:

- [x] Follow the [`CONTRIBUTING` Guide](https://github.com/google-a2a/a2a-js/blob/main/CONTRIBUTING.md).
- [x] Make your Pull Request title in the <https://www.conventionalcommits.org/> specification.
  - Important Prefixes for [release-please](https://github.com/googleapis/release-please):
    - `fix:` which represents bug fixes, and correlates to a [SemVer](https://semver.org/) patch.
    - `feat:` represents a new feature, and correlates to a SemVer minor.
    - `feat!:`, or `fix!:`, `refactor!:`, etc., which represent a breaking change (indicated by the `!`) and will result in a SemVer major.
- [x] Ensure the tests and linter pass
- [x] Appropriate docs were updated (if necessary)

Fixes #157 🦕

### CODE REVIEW

File: src/server/request_handler/default_request_handler.ts [hunk 1]
```diff
@@ -347,7 +347,10 @@ export class DefaultRequestHandler implements A2ARequestHandler {
         const eventBus = this.eventBusManager.getByTaskId(params.id);
         
         if(eventBus) {
+            const eventQueue = new ExecutionEventQueue(eventBus);
             await this.agentExecutor.cancelTask(params.id, eventBus);
+            // Consume all the events until the task reaches a terminal state.
+            await this._processEvents(params.id, new ResultManager(this.taskStore), eventQueue);
```
[the remark this answers is not in the document]
Comment (guglielmo-san) [reply src/server/request_handler/default_request_handler.ts:359]: I do not agree, there is already the await on the cancelTask. Once the cancelTask function completes, a TaskStatusUpdate with TaskStatus="cancelled", must have been published on the eventBus, with a finalState. The _processEvents will consume the produced events until a finalEvent is found on the bus.

File: src/server/request_handler/default_request_handler.ts [hunk 2]
```diff
@@ -370,6 +373,12 @@ export class DefaultRequestHandler implements A2ARequestHandler {
         }
 
         const latestTask = await this.taskStore.load(params.id);
+        if (!latestTask) {
+            throw A2AError.internalError(`Task ${params.id} not found after cancellation.`);
+        }
+        if (latestTask.status.state != "canceled") {
+            throw A2AError.taskNotCancelable(params.id);
```
[the remark this answers is not in the document]
Comment (guglielmo-san) [reply src/server/request_handler/default_request_handler.ts:386]: The intention is to confirm that the cancellation has succeeded, and that the finalEvent found on the eventBus was the cancelled one, as expected

Comment (ishymko) [inline src/server/request_handler/default_request_handler.ts:386]: Can we include resulting state into the error message as [in python](https://github.com/a2aproject/a2a-python/blob/aa159f3e1076ae6eaad5576119d7857c2a9b2448/src/a2a/server/request_handlers/default_request_handler.py#L181)? I think it's useful for debugging.

Comment (ishymko) [inline src/server/request_handler/default_request_handler.ts:386]: Let's add a test case for this branch, i.e. update executor mock to not to emit status update with cancelled.

File: src/server/error.ts [hunk 3]
```diff
@@ -71,10 +71,10 @@ export class A2AError extends Error {
     );
   }
 
-  static taskNotCancelable(taskId: string): A2AError {
+  static taskNotCancelable(errorMessage: string, taskId: string): A2AError {
```
Comment (ishymko) [inline src/server/error.ts]: This will be a public API breaking change (new parameter). Maybe we can do `task: string | Task` and do the type check inside? If the task is passed, we can create an error message with its current status, otherwise keep the old behavior. (Or we can just revert this message change at all)

Comment (guglielmo-san) [reply src/server/error.ts]: I reverted to the original error. I will open an Issue related to "Improvement of Error handling"

File: src/server/request_handler/default_request_handler.ts
Comment (ishymko) [inline src/server/request_handler/default_request_handler.ts:1]: If applicable, let's update the PR description with appropriate failing tck test and reference implementation in Python SDK.
