### PR TITLE
fix: handle json parsing errors in express app

### LINKED ISSUE #146: [Bug]: Not well formatted JSON request does not return a Standard JSON-RPC Errors
### What happened?

When server receives JSON that was not well-formed, it does not return the expected Error Code format 
https://a2a-protocol.org/latest/specification/#81-standard-json-rpc-errors
Instead it returns 
```
SyntaxError: Expected &#39;,&#39; or &#39;}&#39; after property value in JSON at position 305<br> &nbsp; &nbsp;at JSON.parse
```

### Relevant log output

```shell
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>Error</title>
</head>
<body>
<pre>SyntaxError: Expected &#39;,&#39; or &#39;}&#39; after property value in JSON at position 305<br> &nbsp; &nbsp;at JSON.parse (&lt;anonymous&gt;)<br> &nbsp; &nbsp;at parse (/usr/local/google/home/guglielmoc/Desktop/a2a-tck/SUT/javascript_sut/node_modules/body-parser/lib/types/json.js:77:19)<br> &nbsp; &nbsp;at /usr/local/google/home/guglielmoc/Desktop/a2a-tck/SUT/javascript_sut/node_modules/body-parser/lib/read.js:123:18<br> &nbsp; &nbsp;at AsyncResource.runInAsyncScope (node:async_hooks:206:9)<br> &nbsp; &nbsp;at invokeCallback (/usr/local/google/home/guglielmoc/Desktop/a2a-tck/SUT/javascript_sut/node_modules/raw-body/index.js:238:16)<br> &nbsp; &nbsp;at done (/usr/local/google/home/guglielmoc/Desktop/a2a-tck/SUT/javascript_sut/node_modules/raw-body/index.js:227:7)<br> &nbsp; &nbsp;at IncomingMessage.onEnd (/usr/local/google/home/guglielmoc/Desktop/a2a-tck/SUT/javascript_sut/node_modules/raw-body/index.js:287:7)<br> &nbsp; &nbsp;at IncomingMessage.emit (node:events:524:28)<br> &nbsp; &nbsp;at endReadableNT (node:internal/streams/readable:1698:12)<br> &nbsp; &nbsp;at process.processTicksAndRejections (node:internal/process/task_queues:82:21)</pre>
</body>
</html>
```

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by guglielmo-san**
# Description

This PR is adding an error handling middleware to the express server to handle the error triggered by the 
```
router.use(express.json(), ...(middlewares ?? []));
```
and returns and error according to JSON-RPC specification, instead of the general SyntaxError.
This change is required to guarantee the compliance of A2A-js as per [tck tests](https://github.com/a2aproject/a2a-tck).

Thank you for opening a Pull Request!
Before submitting your PR, there are a few things you can do to make sure it goes smoothly:

- [x] Follow the [`CONTRIBUTING` Guide](https://github.com/google-a2a/a2a-js/blob/main/CONTRIBUTING.md).
- [x] Make your Pull Request title in the <https://www.conventionalcommits.org/> specification.
  - Important Prefixes for [release-please](https://github.com/googleapis/release-please):
    - `fix:` which represents bug fixes, and correlates to a [SemVer](https://semver.org/) patch.
    - `feat:` represents a new feature, and correlates to a SemVer minor.
    - `feat!:`, or `fix!:`, `refactor!:`, etc., which represent a breaking change (indicated by the `!`) and will result in a SemVer major.
- [x] Ensure the tests and linter pass
- [x] Appropriate docs were updated (if necessary)

Fixes #146 🦕

### CODE REVIEW

File: src/server/express/a2a_express_app.ts [hunk 1]
```diff
@@ -32,6 +32,20 @@ export class A2AExpressApp {
         const router = express.Router();
         router.use(express.json(), ...(middlewares ?? []));
 
+        router.use((err, req, res, next) => {
+            // Check if it's the specific JSON parsing error
+            if (err instanceof SyntaxError && 'body' in err) {
+                const a2aError = A2AError.parseError('Failed to parse JSON request.');
+                const errorResponse: JSONRPCErrorResponse = {
+                                jsonrpc: '2.0',
+                                id: req.body?.id || null, // Use original request ID if available
```
Comment (ishymko) [inline src/server/express/a2a_express_app.ts]: It seems like the spec says it must be nil if request wasn't parsed: https://a2a-protocol.org/latest/specification/#6112-jsonrpcresponse-object.

File: src/server/express/a2a_express_app.ts [hunk 2]
```diff
@@ -32,6 +32,20 @@ export class A2AExpressApp {
...
+                                error: a2aError.toJSONRPCError(),
+                            };
+                return res.status(500).json(errorResponse);
```
Comment (ishymko) [inline src/server/express/a2a_express_app.ts]: Shouldn't it be 400 bad request?

File: src/server/express/a2a_express_app.ts [hunk 3]
```diff
@@ -32,6 +32,20 @@ export class A2AExpressApp {
         const router = express.Router();
         router.use(express.json(), ...(middlewares ?? []));
 
+        router.use((err, req, res, next) => {
+            // Check if it's the specific JSON parsing error
```
Comment (ishymko) [inline src/server/express/a2a_express_app.ts]: If this is a known issue and there is some prior art, let's reference it in the comment here.

File: src/server/express/a2a_express_app.ts [hunk 4]
```diff
@@ -32,6 +32,20 @@ export class A2AExpressApp {
         const router = express.Router();
         router.use(express.json(), ...(middlewares ?? []));
 
+        router.use((err, req, res, next) => {
```
Comment (ishymko) [inline src/server/express/a2a_express_app.ts:35]: Let's add a unit test for it in `/test/server/a2a_express_app.spec.ts`.

**Review by ishymko — CHANGES_REQUESTED** [review]

File: src/server/express/a2a_express_app.ts (hunk 4 above)
Comment (guglielmo-san) [reply src/server/express/a2a_express_app.ts:35]: Done

File: src/server/express/a2a_express_app.ts [hunk 5]
```diff
@@ -32,6 +32,21 @@ export class A2AExpressApp {
...
+            // This is a bit hacky, but it's the recommended way to catch JSON parsing errors from the `express.json()` middleware.
+            // Express throws a generic SyntaxError and adds a `body` property to it, so we check for both.
+            if (err instanceof SyntaxError && 'body' in err) {
+                const a2aError = A2AError.parseError('Failed to parse JSON request.');
```
Comment (ishymko) [inline src/server/express/a2a_express_app.ts]: nit: can we update the message to be `Invalid JSON payload` as [here](https://a2a-protocol.org/latest/specification/#81-standard-json-rpc-errors)?

File: src/server/express/a2a_express_app.ts [hunk 6]
```diff
@@ -32,6 +32,21 @@ export class A2AExpressApp {
         const router = express.Router();
         router.use(express.json(), ...(middlewares ?? []));
 
+        router.use((err, req, res, next) => {
+            // This is a bit hacky, but it's the recommended way to catch JSON parsing errors from the `express.json()` middleware.
+            // Express throws a generic SyntaxError and adds a `body` property to it, so we check for both.
```
Comment (ishymko) [inline src/server/express/a2a_express_app.ts]: Maybe let's just reference [this issue](https://github.com/expressjs/body-parser/issues/122) instead?

File: test/server/a2a_express_app.spec.ts [hunk 7]
```diff
@@ -335,19 +338,41 @@ describe('A2AExpressApp', () => {
...
 
-            assert.isTrue((mockJsonRpcTransportHandler.handle as SinonStub).calledOnce);
+            assert.isTrue((mockJsonRpcTransportHandler.handle as SinonStub).calledOnceWith(requestBody));
+        });
+
+        it('should handle malformed json request', async () => {
+            const jsonApp = express();
+            app.setupRoutes(jsonApp);
+
+            const requestBody = createMalformedRpcRequest();
```
Comment (ishymko) [inline test/server/a2a_express_app.spec.ts]: nit: I'd inline the string itself here to make it clear and avoid jumping up in the file.

File: test/server/a2a_express_app.spec.ts [hunk 8]
```diff
@@ -335,19 +338,41 @@ describe('A2AExpressApp', () => {
             const jsonApp = express();
             app.setupRoutes(jsonApp);
 
-            const requestBody = { test: 'data' };
+            const requestBody = createRpcRequest('json-test', 'message/send', { test: 'data' });
             (mockJsonRpcTransportHandler.handle as SinonStub).resolves({ 
                 jsonrpc: '2.0', 
                 id: 'json-test', 
-                result: requestBody 
+                result: { success: true }
```
Comment (ishymko) [inline test/server/a2a_express_app.spec.ts]: Why do we need these two updates?

Comment (guglielmo-san) [reply test/server/a2a_express_app.spec.ts]: Just to make it more consistent with the rest of the tests in this file. This test did not make much sense the way it was done before. The mock of the handle function can also be avoided.

File: src/server/express/a2a_express_app.ts [hunk 9]
```diff
@@ -32,6 +32,20 @@ export class A2AExpressApp {
...
 
+        router.use((err, req, res, next) => {
+            // Handle JSON parse errors from express.json() (https://github.com/expressjs/body-parser/issues/122)
+            if (err instanceof SyntaxError && 'body' in err) {
+                const a2aError = A2AError.parseError('Invalid JSON payload.');
+                const errorResponse: JSONRPCErrorResponse = {
+                                jsonrpc: '2.0',
+                                id: null,
+                                error: a2aError.toJSONRPCError(),
+                            };
```
Comment (ishymko) [inline src/server/express/a2a_express_app.ts:43]: nit: formatting

```suggestion
                const errorResponse: JSONRPCErrorResponse = {
                    jsonrpc: '2.0',
                    id: null,
                    error: a2aError.toJSONRPCError(),
                };
```

**Review by ishymko — APPROVED** [review]

File: test/server/a2a_express_app.spec.ts (hunk 7 above)
Comment (ishymko) [reply test/server/a2a_express_app.spec.ts]: nit:

I meant the constant itself:

```ts
const requestBody = '{"jsonrpc": "2.0", "method": "message/send", "id": "1"'; // Missing closing brace
```
Function for this single use case seems redundant.
