### PR TITLE
fix: Populate the ServerCallContext user param when a new ServerCallContext is created

### LINKED ISSUE #199: [Bug]: The user set by authentication is removed from the server call context
### What happened?

The server call context does not contain the user create and authenticated

### Relevant log output

```shell

```

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by guglielmo-san**
# Description

This PR is a fix for the bug caused by the user being deleted when the request is containing requested extensions, as a new ServerCallContext was created without copying the `context.user`.

Fixes #199 🦕
PRs #171, #195 

BEGIN_COMMIT_OVERRIDE
refactor: Populate the ServerCallContext user param when a new ServerCallContext is created
END_COMMIT_OVERRIDE

### CODE REVIEW

File: src/server/request_handler/default_request_handler.ts
Comment (ishymko) [inline src/server/request_handler/default_request_handler.ts]: nit: can we initialize with `context` here instead and omit `?? context` below? Or maybe even override parameter itself and do not create `newServerCallContext`.

File: src/server/request_handler/default_request_handler.ts [hunk 1]
```diff
@@ -143,7 +135,7 @@ export class DefaultRequestHandler implements A2ARequestHandler {
           exposedExtensions.has(extension)
         )
       );
-      newServerCallContext = new ServerCallContext(validExtensions);
+      newServerCallContext = new ServerCallContext(validExtensions, context.user);
```
Comment (ishymko) [inline src/server/request_handler/default_request_handler.ts]: Should we make `User` a mandatory parameter in `ServerCallContext` to avoid such things? This type wasn't released yet, so it's not going to be a breaking change.

File: src/server/index.ts [hunk 2]
```diff
@@ -29,4 +28,5 @@ export type { DefaultPushNotificationSenderOptions } from './push_notification/d
 export type { PushNotificationStore } from './push_notification/push_notification_store.js';
 export { InMemoryPushNotificationStore } from './push_notification/push_notification_store.js';
 
-export type { User, UnauthenticatedUser } from './authentication/user.js';
+export type { User } from './authentication/user.js';
+export { UnauthenticatedUser } from './authentication/user.js';
```
Comment (ishymko) [inline src/server/index.ts:33]: Is it intentional?

File: src/server/request_handler/default_request_handler.ts
Comment (ishymko) [inline src/server/request_handler/default_request_handler.ts:1]: Can we link PR(s) which introduced the original code in the description? 

Also let's use `BEGIN_COMMIT_OVERRIDE` to avoid including this into the changelog. The code under fix wasn't released yet, so from the end user perspective it's not a fix from the previous version, just a new functionality. PR title makes sense though. I.e.

```
BEGIN_COMMIT_OVERRIDE
refactor: Populate the ServerCallContext user param when a new ServerCallContext is created
END_COMMIT_OVERRIDE
```

File: src/server/request_handler/default_request_handler.ts (hunk 1 above)
Comment (guglielmo-san) [reply src/server/request_handler/default_request_handler.ts]: Uhm I am not fully convinced on this, but in any case i would do it in a different PR

File: src/server/index.ts (hunk 2 above)
Comment (guglielmo-san) [reply src/server/index.ts:33]: Yes, the Unauthenticated user was exported as a type, but actually it is a class. It is a small item, and i noticed it writing the test for this PR, i don't think it is necessary to separate in an ad hoc PR

**Review by ishymko — APPROVED** [review]
